### ISSUE TITLE
Add additional linters for LaTeX

### ISSUE THREAD

**Issue by robert-7** [robert-7/Math-Assignments-and-Presentations#15]
Add additional linters for LaTeX files

```yaml
- id: csquotes
  name: All quotation marks should use csquotes
  description: Ensure the use of LaTeX csquotes and prohibits manual quotation marks.
  entry: "``.*''|''.*''"
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: ensure-labels-for-sections
  name: Ensure each section has a matching label
  entry: ensure-labels
  language: rust
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
```
